base_path: .
pull_request_title: Crowdin Translations
commit_message: 'New translations for {languageName}'
files:
  - source: /resources/i18n/flycast.pot
    translation: /resources/i18n/%two_letters_code%.po
    languages_mapping:
      two_letters_code:
        zh-CN: zh_CN
        zh-TW: zh_TW
        zh-HK: zh_HK
        en-GB: en_GB
        pt-BR: pt_BR
  - source: /shell/android-studio/flycast/src/main/res/values/strings.xml
    translation: /shell/android-studio/flycast/src/main/res/values-%two_letters_code%/strings.xml
    languages_mapping:
      two_letters_code:
        zh-CN: zh-rCN
        zh-TW: zh-rTW
        zh-HK: zh-rHK
        en-GB: en-rGB
        pt-BR: pt-rBR
