#pragma once

#include "ir_defs.h"

namespace sh4 {
namespace ir {

// Autogenerated lookup tables for opcode -> IR Op.
// kEmitterTable is used by the IR emitter, kExecutorTable by the executor.
// Both are 65536-entry arrays (one per 16-bit SH-4 opcode).
// We expose the tables as const pointers to the first element; size is 65536.
extern const Op* kEmitterTable;
extern const Op* kExecutorTable;

} // namespace ir
} // namespace sh4
