#!/usr/bin/env python3
"""Regenerate the synthetic 7z fixtures (requires 7z or 7zz).

No game data is used. Raw sectors contain a track/frame marker followed by zeros;
the CHD fixture is the synthetic image generated by ../test_chds/make_fixtures.py.
Archive timestamps and header compression are disabled for reproducible fixtures.
"""

from pathlib import Path
import shutil
import struct
import subprocess
import tempfile

HERE = Path(__file__).resolve().parent
SECTOR = 2352


def sectors(track, count=4):
    return b"".join(bytes([track, 0x11, frame, 0x22, 0, 0x33, 0x44, 0x55])
                    + bytes(SECTOR - 8) for frame in range(count))


def cdi():
    """Minimal DiscJuggler v2 image: one session, two four-sector tracks."""
    data = sectors(1) + sectors(2)
    header = bytearray(struct.pack("<HH", 1, 2))
    start_mark = b"\0\0\x01\0\0\0\xff\xff\xff\xff"
    for mode, start in ((1, 150), (0, 154)):
        header += bytes(4) + start_mark * 2 + bytes(4)
        header += bytes(1 + 19 + 4 + 2)  # no filename or extra header data
        header += struct.pack("<II", 0, 4)  # pregap and sector count
        header += bytes(6) + struct.pack("<I", mode) + bytes(12)
        header += struct.pack("<II", start, 4) + bytes(16)
        header += struct.pack("<I", 2) + bytes(29)  # 2352-byte raw sectors
    header += bytes(12)  # session trailer
    return data + header + struct.pack("<II", 0x80000004, len(data))


def build(tool, name, files, solid=True, rename=None):
    output = HERE / name
    output.unlink(missing_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        for filename, data in files.items():
            path = Path(tmp) / filename
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data.encode("utf-8") if isinstance(data, str) else data)
        subprocess.run([tool, "a", "-t7z", "-mx=5", "-m0=lzma2",
                        "-ms=on" if solid else "-ms=off", "-mtc=off",
                        "-mtm=off", "-mta=off", "-mhc=off", str(output),
                        *sorted(files)], cwd=tmp, check=True, stdout=subprocess.DEVNULL)
    if rename:
        subprocess.run([tool, "rn", "-mhc=off", str(output), *rename],
                       check=True, stdout=subprocess.DEVNULL)
    print(f"{name}: {output.stat().st_size} bytes")


def main():
    tool = shutil.which("7zz") or shutil.which("7z")
    if not tool:
        raise SystemExit("7z or 7zz is required to regenerate fixtures")

    gdi = ('3\n1 0 4 2352 "tracks/track 01.bin" 0\n'
           '2 450 0 2352 "tracks/音声 02.raw" 0\n'
           '3 45000 4 2352 "tracks/track 03.bin" 0\n')
    prefix = "nested/ゲーム 🎮/"
    gdi_files = {prefix + "disc.GDI": gdi,
                 prefix + "tracks/track 01.bin": sectors(1),
                 prefix + "tracks/音声 02.raw": sectors(2),
                 prefix + "tracks/track 03.bin": sectors(3, 40)}
    build(tool, "gdi-solid.7z", gdi_files)
    build(tool, "gdi-nonsolid.7z", gdi_files, solid=False)
    # Names longer than the former fixed 512-code-unit name buffer.
    long_prefix = "/".join(["long-directory-" + "x" * 90] * 5) + "/"
    build(tool, "long-path.7z", {long_prefix + name: data
                                for name, data in gdi_files.items()})

    cue = ('FILE "tracks/shared.bin" BINARY\n'
           '  TRACK 01 MODE1/2352\n    INDEX 01 00:00:00\n'
           '  TRACK 02 AUDIO\n    INDEX 01 00:00:04\n'
           '  TRACK 03 MODE1/2352\n    INDEX 01 00:00:08\n')
    build(tool, "cue-shared.7z", {"disc/game.cue": cue,
          "disc/tracks/shared.bin": sectors(1) + sectors(2) + sectors(3)})
    build(tool, "chd.7z", {"nested/AUDIO.CHD":
          (HERE.parent / "test_chds/audiocd.chd").read_bytes()})
    build(tool, "cdi.7Z", {"nested/disc.CDI": cdi()})
    build(tool, "archive.7z", {"payload.bin": bytes(i % 251 for i in range(131073)),
          "empty": b"", "folder/日本語😀.bin": b"utf8"})
    build(tool, "no-disc.7z", {"readme.txt": "Synthetic fixture, no disc image.\n"})
    build(tool, "multiple-discs.7z", {"disc1.cue": cue, "disc2.cue": cue})
    build(tool, "mixed-descriptors.7z", {"game.gdi": gdi, "game.cue": cue})
    build(tool, "missing-track.7z", {"disc.gdi": gdi,
          "tracks/track 01.bin": sectors(1)})
    build(tool, "invalid-descriptor.7z", {"disc.gdi": "not a GDI\n"})
    build(tool, "traversal-track.7z", {"disc.cue":
          'FILE "../test_gdis/b/cs01.bin" BINARY\n'
          '  TRACK 01 MODE1/2352\n    INDEX 01 00:00:00\n'})
    build(tool, "traversal-entry.7z", gdi_files,
          rename=(prefix + "disc.GDI", "../disc.gdi"))
    valid = (HERE / "gdi-solid.7z").read_bytes()
    (HERE / "truncated.7z").write_bytes(valid[:40])
    corrupt = bytearray(valid)
    corrupt[40] ^= 0xFF  # corrupt packed data, preserving the header
    (HERE / "corrupt-data.7z").write_bytes(corrupt)


if __name__ == "__main__":
    main()
