name: BSD

on:
  push:
    branches-ignore:
      - 'l10n_**'
  pull_request:

jobs:
  build:
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating_system: [ freebsd, netbsd, openbsd ]
        architecture: [ arm64, x86-64 ]
        libretro: [ OFF, ON ]
        include:
          - operating_system: freebsd
            version: '15.1'
            pkginstall: sudo pkg upgrade -y && sudo pkg install -y alsa-lib ccache cmake evdev-proto git libao libcdio libevdev libudev-devd libzip lua54 miniupnpc ninja pkgconf pulseaudio sdl2
          - operating_system: netbsd
            version: '11.0'
            pkginstall: sudo pkgin update && sudo pkgin -y install alsa-lib ccache clang cmake git libao libcdio libusb1-1.0.30 libzip lua54 miniupnpc ninja-build pkgconf pulseaudio SDL2
          - operating_system: openbsd
            version: '7.9'
            pkginstall: sudo pkg_add -u && sudo pkg_add ccache cmake git libao libcdio libusb1-1.0.29 libzip lua-5.4.8p0 miniupnpc ninja pulseaudio sdl2
        exclude:
          - architecture: arm64

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions/cache@v6
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.operating_system }}-${{ matrix.architecture }}-${{ matrix.libretro }}-${{ github.sha }}
          restore-keys: ccache-${{ matrix.operating_system }}-${{ matrix.architecture }}-${{ matrix.libretro }}-

      - name: Start VM
        uses: cross-platform-actions/action@v1
        with:
          operating_system: ${{ matrix.operating_system }}
          architecture: ${{ matrix.architecture }}
          version: ${{ matrix.version }}
          environment_variables: CCACHE_DIR

      - name: Set up build environment
        run: ${{ matrix.pkginstall }}
        shell: cpa.sh {0}

      - name: CMake
        run: |
          cmake -B build -DUSE_LIBCDIO=ON -DCMAKE_BUILD_TYPE=Release -G Ninja -DLIBRETRO=${{ matrix.libretro }}
          cmake --build build --config Release
        shell: cpa.sh {0}
